Repository wecode-bootcamp-korea/35-1st-2sa-living-backend, pull requests merged in 2022-07, with the labels that each got.

#2 [35기 2사리빙] ADD : models.py
  _2sa_living/settings.py
  carts/__init__.py
  carts/admin.py
  carts/apps.py
  carts/migrations/0001_initial.py
  carts/migrations/0002_rename_product_id_cart_product_and_more.py
  carts/migrations/__init__.py
  carts/models.py
  carts/tests.py
  carts/views.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_rename_order_status_id_order_order_status_and_more.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/0001_initial.py
  products/migrations/0002_rename_furniture_product_furniture.py
  products/migrations/0003_rename_cololr_product_color_and_more.py
  products/migrations/0004_alter_product_price.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: 완료

#3 [35기 2사리빙_현진] ADD: products app, models.py 수정
  products/migrations/0005_color_english_name_furniture_english_name.py
  products/models.py
Labels: 완료

#4 [35기 2사리빙 이원재] ADD : signup login views.py 작성
  _2sa_living/settings.py
  _2sa_living/urls.py
  users/urls.py
  users/views.py
Labels: 완료

#8 [35기 2사리빙 김민지]Modify: cartsApp, ordersApp migrate 오류수정
  carts/migrations/0001_initial.py
  carts/migrations/0002_initial.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_initial.py
Labels: 완료

#12 [35기 2사리빙 김민지] ADD: core App - utils.py
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/utils.py
  core/views.py
Labels: 완료

#10 [35기 2사리빙 홍현진] products/views.py - DetailView
  .gitignore
  _2sa_living/urls.py
  products/models.py
  products/urls.py
  products/views.py
Labels: 완료

#13 [35기 2사리빙 김민지] ADD: carts APP의 views.py - GET 메소드 작성
  _2sa_living/urls.py
  carts/urls.py
  carts/views.py
  core/utils.py
Labels: 완료

#11 [35기 2사리빙 김민지] feature/cartsApp/CartView-POST
  _2sa_living/urls.py
  carts/views.py
Labels: 완료

#17 [35기 2사리빙 김민지] feature/usersApp/views.py의 LikeView - POST
  users/urls.py
  users/views.py
Labels: 완료

#19 [35기 2사리빙 홍현진 ] 프론트 요청으로 ProductDetailView, 반환하는 brand랑 price 추가
  products/views.py
Labels: 완료

#14 [35기 2사리빙 김민지] ADD: carts APP의 views.py - DELETE 메소드 작성
  _2sa_living/urls.py
  carts/urls.py
  carts/views.py
Labels: 완료

#16 [35기 이사리빙 이원재] ADD : OrderView GET
  _2sa_living/urls.py
  orders/urls.py
  orders/views.py
Labels: 완료

#15 [35기 이사리빙 이원재] ADD : OrderView POST
  orders/urls.py
  orders/views.py
Labels: 수정 요청

#20 [35기 2사리빙 김민지] MODIFY: ordersAPP의 CartListView 수정
  orders/urls.py
  orders/views.py
Labels: 멘토 리뷰 요청
